// Explicitly reviewed selection: one file per entry, never count a source website as a resource.
export const packId = 'resources-20260916';
export const isExpansionAssetPath = value => typeof value === 'string' && /^expansion\/(?:models\/[a-z0-9][a-z0-9._-]*\.glb|panoramas\/[a-z0-9][a-z0-9._-]*\.jpg)$/.test(value);
export const nasaRevision = '11ebb4ee043715aefbba6aeec8a61746fad67fa7';
export const nasaGuidelines = 'https://www.nasa.gov/nasa-brand-center/images-and-media/';
export const nasaReadme = `https://github.com/nasa/NASA-3D-Resources/blob/${nasaRevision}/README.md`;
export const excludedModels = [
  {path:'3D Models/Terra/Terra.glb',reason:'GLB 引用未随仓库提供的 Terra.fbm/Side_Panels_TERRA.tga 和 solarpanels.tga；待取得贴图并重新打包后接入。'},
  {path:'3D Models/Regolith Advanced Surface Systems Operations Robot (RASSOR)/Regolith Advanced Surface Systems Operations Robot (RASSOR).glb',reason:'GLB 的 TRIANGLES 索引声明为 2029759 面，超过平台 2000000 面限制；入库返回 400。原文件未修改，待单独制作并验收减面版本。'},
];
const nasa = (folder,title,category,file=folder) => ({provider:'nasa',path:`3D Models/${folder}/${file}.glb`,title,category});
export const modelSelection = [
  nasa('Mars 2020 Perseverance Rover','毅力号火星车','航天探索'),
  nasa('Ingenuity Mars Helicopter','机智号火星直升机','航天探索'),
  nasa('Viking Lander','维京号火星着陆器','航天探索'),
  nasa('InSight Cruise Lander','洞察号着陆器 · 机械臂展开','航天探索','InSight Cruise Lander (arm deployed)'),
  nasa('Mars Odyssey','火星奥德赛探测器','航天探索'),
  nasa('Mars Reconnaissance Orbiter (MRO) (A)','火星勘测轨道飞行器 MRO','航天探索'),
  nasa('Mars Global Surveyor','火星全球勘测者','航天探索'),
  nasa('Mars Atmosphere and Volatile EvolutioN (MAVEN) (A)','火星大气探测器 MAVEN','航天探索'),
  nasa('Juno (A)','朱诺号木星探测器','航天探索'),
  nasa('Cassini-Huygens (A)','卡西尼—惠更斯探测器','航天探索'),
  nasa('Galileo','伽利略号探测器','航天探索'),
  nasa('Dawn','黎明号探测器','航天探索'),
  nasa('Deep Impact (EPOXI)','深度撞击号探测器','航天探索','Deep Impact'),
  nasa('Deep Space 1','深空一号探测器','航天探索'),
  nasa('Origins, Spectral Interpretation, Resource Identification, and Security - Regolith Explorer (OSIRIS-REx)','小行星采样探测器 OSIRIS-REx','航天探索','OSIRIS-REx'),
  nasa('NEAR Shoemaker','舒梅克号小行星探测器','航天探索'),
  nasa('Pioneer 10','先驱者十号探测器','航天探索'),
  nasa('Voyager Probe (A)','旅行者号探测器','航天探索'),
  nasa('Apollo Lunar Module','阿波罗登月舱','航天工程'),
  nasa('Gemini','双子座飞船','航天工程'),
  nasa('Apollo Soyuz','阿波罗—联盟号对接组合','航天工程'),
  nasa('Saturn V','土星五号运载火箭','航天工程'),
  nasa('Space Shuttle (A)','航天飞机','航天工程'),
  nasa('International Space Station (ISS) (B)','国际空间站 ISS','航天工程'),
  nasa('Skylab','天空实验室空间站','航天工程'),
  nasa('Hubble Space Telescope (A)','哈勃空间望远镜','天文观测'),
  nasa('James Webb Space Telescope (A)','詹姆斯·韦布空间望远镜','天文观测'),
  nasa('Chandra X-ray Observatory','钱德拉 X 射线天文台','天文观测'),
  nasa('Spitzer Space Telescope','斯皮策空间望远镜','天文观测'),
  nasa('Kepler (A)','开普勒空间望远镜','天文观测'),
  nasa('Nancy Grace Roman Space Telescope (A)','南希·格雷斯·罗曼空间望远镜','天文观测'),
  nasa('Transiting Exoplanet Survey Satellite (TESS) (A)','凌日系外行星巡天卫星 TESS','天文观测'),
  nasa('Fermi Gamma-ray Large Area Space Telescope','费米伽马射线空间望远镜','天文观测'),
  nasa('Landsat 8','陆地卫星八号 Landsat 8','地球观测'),
  nasa('Aqua (A)','Aqua 地球观测卫星','地球观测'),
  nasa('Aura (A)','Aura 大气观测卫星','地球观测'),
  nasa('Terra','Terra 地球观测卫星','地球观测'),
  nasa('Global Precipitation Measurement','全球降水测量卫星 GPM','地球观测'),
  nasa('Gravity Recovery and Climate Experiment (GRACE) (B)','重力恢复与气候实验卫星 GRACE','地球观测'),
  nasa('Ice, Clouds, and Land Elevation Satellite-2 (ICESat-2) (A)','冰、云和陆地高程卫星 ICESat-2','地球观测'),
  nasa('Parker Solar Probe','帕克太阳探测器','天文观测'),
  nasa('Solar Dynamics Observatory','太阳动力学天文台 SDO','天文观测'),
  nasa('Solar and Heliospheric Observatory','太阳与日球层天文台 SOHO','天文观测'),
  nasa('Solar TErrestrial RElations Observatory (STEREO)','日地关系天文台 STEREO','天文观测'),
  nasa('Robonaut 2','机器人宇航员 Robonaut 2','航天工程'),
  nasa('Regolith Advanced Surface Systems Operations Robot (RASSOR)','表土挖掘机器人 RASSOR','航天工程'),
  nasa('Deep Space Network 70-meter','深空网络 70 米天线','航天工程'),
  nasa('Vehicle Assembly Building (VAB)','运载火箭装配大楼 VAB','航天工程'),
];
export const panoramaSelection = [
  ['surgery','手术室 · 医疗空间','人体与健康','观察手术室的灯具、设备和通行空间；仅作环境认识，不提供临床操作指引。'],
  ['vintage_measuring_lab','历史测量实验室','物理工程','寻找仪器、工作台和采光方向，比较不同操作区域的布局。'],
  ['university_workshop','大学工程实验车间','物理工程','观察工作台、设备与走道的空间关系，区分操作和通行区域。'],
  ['boiler_room','锅炉房 · 工业设备环境','物理工程','环顾管线、设备和维护空间；画出能直接观察到的连接关系。'],
  ['smelting_tower_interior','冶炼塔内部','物理工程','抬头和低头观察塔内结构，比较不同高度的设备和平台。'],
  ['abandoned_waterworks','旧水处理设施','物理工程','观察水工设施与建筑遗存，不把外观直接当作仍在运行的工艺证据。'],
  ['carpentry_shop_01','木工车间','物理工程','观察加工、存放和通行空间，寻找工作台与工具的布置特点。'],
  ['abandoned_hopper_terminal_01','旧料斗装卸站','物理工程','观察料斗、支撑结构和通道的相对位置。'],
  ['whale_skeleton','鲸骨架展陈空间','自然科学','环顾骨架展陈，观察脊柱、肋骨与展厅尺度的关系。'],
  ['ushaka_sea_world_aquarium','海洋水族馆','自然科学','观察水族箱、观看通道和光线如何共同组织参观空间。'],
  ['abandoned_greenhouse','旧温室 · 设施农业','生态环境','观察温室骨架、透光材料和植物环境之间的关系。'],
  ['aloe_farm_shade_house','芦荟农场遮阴棚','生态环境','比较遮阴棚、植物排列与通行区域，思考遮阴对光照的影响。'],
  ['citrus_orchard','柑橘果园','生态环境','观察树木排列、地面与行间通道，比较人工种植和自然林地。'],
  ['arboretum','树木园','生态环境','比较近处与远处植物的层次、遮挡和冠层形态。'],
  ['rainforest_trail','雨林步道','生态环境','观察冠层、林下植物与地表，记录不同高度的植被层次。'],
  ['blue_grotto','蓝色洞穴 · 林间水潭','地理环境','环顾岩壁、水面与洞口，比较明暗和不同方向的地貌形态。'],
  ['small_cave','洞穴内部','地理环境','寻找洞口、顶壁和底面，描述封闭空间与外界光照的关系。'],
  ['crystal_falls','瀑布与岩壁','地理环境','观察水流、岩壁和周边植被的相对位置，描述可见地形起伏。'],
  ['table_mountain_1','桌山 · 山地景观','地理环境','比较近处山体、远处地平线和天空，辨认地形轮廓。'],
  ['valley_of_desolation','荒凉谷 · 岩柱地貌','地理环境','观察岩体、坡面和远景，不从单张全景推断精确年代或成因。'],
  ['snowy_forest','积雪森林','生态环境','比较树干、枝叶和地表积雪，观察冬季环境的空间层次。'],
  ['river_rocks','河流与岩石','地理环境','观察河道、水面和两岸岩石，记录水陆交界的形态。'],
  ['shudu_lake','属都湖 · 高原湖泊','地理环境','环顾湖岸、远山与植被，比较不同距离的景观层次。'],
  ['cliffside','悬崖边缘 · 地形观察','地理环境','观察坡面、岩壁与远景，理解高差和视线遮挡。'],
  ['aristea_wreck','Aristea 沉船遗址','历史与工程','观察船体残存结构及其周围环境，区分可见事实与复原推测。'],
  ['dam_wall','水坝坝墙','物理工程','观察坝墙、道路与水体的位置关系，描述可见的防护结构。'],
  ['railway_bridges','铁路桥梁群','物理工程','比较桥墩、梁体和通行空间，辨认桥梁的主要承重构件。'],
  ['chinese_garden','中式园林空间','历史与建筑','观察建筑、水体、植物与游览路径，描述借景和遮挡关系。'],
  ['zhengyang_gate','正阳门 · 城市历史空间','历史与建筑','环顾城门及周边空间，观察城门、道路和广场的尺度关系。'],
  ['colosseum','罗马斗兽场','历史与建筑','观察环形建筑、拱券和参观空间，比较内外部结构。'],
  ['sculpture_exhibition','雕塑展厅','历史与建筑','比较展品、观看距离和展厅采光，讨论展陈空间的组织。'],
  ['reading_room','阅览室 · 公共学习空间','社会与环境','观察座位、书架、窗户与通道，比较阅读和流通区域。'],
].map(([id,title,category,description])=>({provider:'polyhaven',id,title,category,description}));
